CREATE TABLE paid_ads_performance (
    date DATE,
    add_to_cart INT64,
    clicks INT64,
    comments INT64,
    engagements INT64,
    impressions INT64,
    installs INT64,
    likes INT64,
    link_clicks INT64,
    post_click_conversions INT64,
    post_view_conversions INT64,
    posts INT64,
    purchase INT64,
    registrations INT64,
    revenue INT64,
    shares INT64,
    spend INT64,
    total_conversions INT64,
    video_views INT64,
    ad_id STRING,
    adset_id STRING,
    campaign_id STRING,
    channel STRING,
    creative_id STRING,
    placement_id STRING
);