SELECT
    date,
    NULL as add_to_cart, 
    clicks,
    NULL as comments,
    NULL as engagements,
    NULL as impressions,
    NULL as installs,
    NULL as likes,
    NULL as link_clicks,
    NULL as post_click_conversions,
    NULL as post_view_conversions,
    NULL as posts,
    NULL as purchase,
    NULL as registrations,
    NULL as revenue,
    NULL as shares,
    spend,
    conv as total_conversions,
    NULL as video_views,
    ad_id,
    adset_id,
    campaign_id,
    channel,
    NULL as creative_id,
    NULL as placement_id
FROM {{ source('dbt_ulbonchik', 'src_ads_bing_all_data') }}