SELECT
    date,
    add_to_cart,
    clicks, 
    comments,
    (likes + shares + comments + views) AS engagements, -- we create engagements field by adding views, likes, shares and comments
    impressions,
    mobile_app_install as installs,
    likes,
    inline_link_clicks as link_clicks,
    NULL as post_click_conversions,
    NULL as post_view_conversions,
    NULL as posts,
    purchase,
    complete_registration as registrations,
    (purchase_value - spend) as revenue,
    shares,
    spend,
    purchase as total_conversions,
    NULL as video_views,
    ad_id,
    adset_id,
    campaign_id,
    channel,
    creative_id,
    NULL as placement_id
FROM {{ source('dbt_ulbonchik', 'src_ads_creative_facebook_all_data')}}	