SELECT
    date,
    add_to_cart,
    clicks,
    NULL as comments,
    NULL as engagements,
    impressions,
    (rt_installs + skan_app_installs) as installs,
    NULL as likes,
    NULL as link_clicks,
    NULL as post_click_conversions,
    NULL as porst_view_conversions,
    NULL as posts,
    purchase,
    registrations,
    NULL as revenue,
    NULL as shares,
    spend,
    conversitions as total_conversions,
    video_views,
    ad_id,
    adset_id,
    campaign_id,
    channel,
    NULL as creative_id,
    NULL as placement_id
FROM {{ source('dbt_ulbonchik', 'src_ads_tiktok_ads_all_data') }}