SELECT
    date,
    NULL as add_to_cart,
    clicks,
    comments,
    engagements,
    impressions,
    NULL as installs,
    likes,
    url_clicks as link_clicks,
    NULL as post_click_conversions,
    NULl as post_views_conversions,
    NULL as posts,
    NULL as purchase,
    NULL as registrations,
    NULL as revenue,
    retweets as shares,
    spend,
    NULL as total_conversions,
    video_total_views,
    url as ad_id,
    NULL as adset_id,
    campaign_id,
    channel,
    NULL as creative_id,
    NULL as placement_id
FROM {{ source('dbt_ulbonchik', 'src_promoted_tweets_twitter_all_data') }}